name             'pointize_cookbook'
maintainer       'Bizsciences'
maintainer_email 'balaji@holidayjuggle.net'
license          'Apache 2.0'
description      'Installs/Configures pointize_cookbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'build-essential'
depends          'apache2', '>= 2.0'
depends          'java'
depends          'tomcat6'
